In [1]:
import torch

### PyTorch Version

In [2]:
print(torch.__version__)

2.6.0+cu124


### Cuda info

In [3]:
!nvidia-smi

Tue May  6 13:22:20 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.163.01             Driver Version: 550.163.01     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3080        Off |   00000000:01:00.0  On |                  N/A |
| 47%   39C    P8             29W /  350W |   10426MiB /  12288MiB |     25%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### PyTorch default settings

In [4]:
display(torch.get_default_dtype())
display(torch.get_default_device())

torch.float32

device(type='cpu')

### Scalar

In [9]:
tens_0 = torch.rand(size=(), dtype=None, device=None, requires_grad=False)
print(f"tens_0 ndim: {tens_0.ndim}, shape {tens_0.shape}, requires_grad {tens_0.requires_grad}, dtype {tens_0.dtype} device {tens_0.device}")
display(tens_0)

tens_gpu_0 = torch.rand(size=(), dtype=None, device='cuda', requires_grad=False)
print(f"tens_gpu_0 ndim: {tens_gpu_0.ndim}, shape {tens_gpu_0.shape}, requires_grad {tens_gpu_0.requires_grad}, dtype {tens_gpu_0.dtype} device {tens_gpu_0.device}")
display(tens_gpu_0)

tens_0 ndim: 0, shape torch.Size([]), requires_grad False, dtype torch.float32 device cpu


tensor(0.0038)

tens_gpu_0 ndim: 0, shape torch.Size([]), requires_grad False, dtype torch.float32 device cuda:0


tensor(0.9720, device='cuda:0')

### Vector

In [10]:
tens_1 = torch.rand(size=(3,), dtype=None, device=None, requires_grad=False)
print(f"tens_1 ndim: {tens_1.ndim}, shape {tens_1.shape}, requires_grad {tens_1.requires_grad}, dtype {tens_1.dtype} device {tens_1.device}")
display(tens_1)

tens_gpu_1 = torch.rand(size=(3,), dtype=None, device='cuda', requires_grad=False)
print(f"tens_gpu_1 ndim: {tens_gpu_1.ndim}, shape {tens_gpu_1.shape}, requires_grad {tens_gpu_1.requires_grad}, dtype {tens_gpu_1.dtype} device {tens_gpu_1.device}")
display(tens_gpu_1)

tens_1 ndim: 1, shape torch.Size([3]), requires_grad False, dtype torch.float32 device cpu


tensor([0.4049, 0.7345, 0.3481])

tens_gpu_1 ndim: 1, shape torch.Size([3]), requires_grad False, dtype torch.float32 device cuda:0


tensor([0.9028, 0.2098, 0.7335], device='cuda:0')

### Matrix

In [11]:
tens_2 = torch.rand(size=(3, 4), dtype=None, device=None)
print(f"tens_2 ndim: {tens_2.ndim}, shape {tens_2.shape}, requires_grad {tens_2.requires_grad}, dtype {tens_2.dtype}, device {tens_2.device}")
display(tens_2)

tens_gpu_2 = torch.rand(size=(3, 4), dtype=None, device='cuda', requires_grad=False)
print(f"tens_gpu_2 ndim: {tens_gpu_2.ndim}, shape {tens_gpu_2.shape}, requires_grad {tens_gpu_2.requires_grad}, dtype {tens_gpu_2.dtype} device {tens_gpu_2.device}")
display(tens_gpu_2)

tens_2 ndim: 2, shape torch.Size([3, 4]), requires_grad False, dtype torch.float32, device cpu


tensor([[0.6560, 0.7023, 0.5975, 0.2189],
        [0.1764, 0.7195, 0.8631, 0.6895],
        [0.0937, 0.3998, 0.9137, 0.6023]])

tens_gpu_2 ndim: 2, shape torch.Size([3, 4]), requires_grad False, dtype torch.float32 device cuda:0


tensor([[0.0885, 0.4325, 0.2230, 0.0068],
        [0.8494, 0.1105, 0.0896, 0.9383],
        [0.6968, 0.5547, 0.1479, 0.0256]], device='cuda:0')

### Tensor

In [13]:
tens_3 = torch.rand(size=(5, 4, 3), dtype=None, device=None)
print(f"tens_3 ndim: {tens_3.ndim}, shape {tens_3.shape}, requires_grad {tens_3.requires_grad}, dtype {tens_3.dtype}, device {tens_3.device}")
display(tens_3)

tens_gpu_3 = torch.rand(size=(5, 4, 3), dtype=None, device='cuda', requires_grad=False)
print(f"tens_gpu_3 ndim: {tens_gpu_3.ndim}, shape {tens_gpu_3.shape}, requires_grad {tens_gpu_3.requires_grad}, dtype {tens_gpu_3.dtype} device {tens_gpu_3.device}")
display(tens_gpu_3)

tens_3 ndim: 3, shape torch.Size([5, 4, 3]), requires_grad False, dtype torch.float32, device cpu


tensor([[[0.6127, 0.4937, 0.3737],
         [0.1833, 0.2508, 0.3210],
         [0.9242, 0.3690, 0.3014],
         [0.6134, 0.7216, 0.5169]],

        [[0.9880, 0.6350, 0.7963],
         [0.2793, 0.4112, 0.8320],
         [0.5989, 0.4759, 0.0760],
         [0.8501, 0.5075, 0.9394]],

        [[0.1370, 0.7787, 0.1632],
         [0.6403, 0.3949, 0.6311],
         [0.1667, 0.1497, 0.0855],
         [0.4844, 0.3968, 0.9076]],

        [[0.2653, 0.5209, 0.5230],
         [0.9148, 0.3693, 0.4530],
         [0.0183, 0.0986, 0.2594],
         [0.5154, 0.1977, 0.9639]],

        [[0.8786, 0.4120, 0.1120],
         [0.4771, 0.1534, 0.8716],
         [0.4368, 0.7637, 0.7028],
         [0.4131, 0.7037, 0.8118]]])

tens_gpu_3 ndim: 3, shape torch.Size([5, 4, 3]), requires_grad False, dtype torch.float32 device cuda:0


tensor([[[0.3652, 0.3344, 0.0765],
         [0.1005, 0.1281, 0.6179],
         [0.7534, 0.0158, 0.5803],
         [0.5402, 0.6321, 0.5069]],

        [[0.2517, 0.6963, 0.8803],
         [0.2986, 0.1276, 0.2859],
         [0.3521, 0.2503, 0.8741],
         [0.8774, 0.6897, 0.1239]],

        [[0.3514, 0.1734, 0.2755],
         [0.6714, 0.3219, 0.6329],
         [0.3219, 0.6464, 0.7811],
         [0.2872, 0.1971, 0.1406]],

        [[0.7809, 0.0637, 0.7697],
         [0.4411, 0.7388, 0.6237],
         [0.6517, 0.7068, 0.4645],
         [0.0871, 0.9812, 0.8184]],

        [[0.9034, 0.1986, 0.8990],
         [0.7193, 0.3138, 0.6373],
         [0.6011, 0.7158, 0.6255],
         [0.1629, 0.3631, 0.2973]]], device='cuda:0')

### Tensor Operations

In [24]:
tens_2a = torch.rand(size=(4,2), dtype=torch.float32, device='cuda', requires_grad=False)
tens_2b = torch.rand(size=(4,2), dtype=torch.float32, device='cuda', requires_grad=False)

In [25]:
print(f"tens_2a ndim: {tens_2a.ndim}, shape {tens_2a.shape}, requires_grad {tens_2a.requires_grad}, dtype {tens_2a.dtype}, device {tens_2a.device}")
display(tens_2a)
print(f"tens_2b ndim: {tens_2b.ndim}, shape {tens_2b.shape}, requires_grad {tens_2b.requires_grad}, dtype {tens_2b.dtype}, device {tens_2b.device}")
display(tens_2b)

tens_2b_T = tens_2b.transpose(1,0)
print(f"tens_2b_T ndim: {tens_2b_T.ndim}, shape {tens_2b_T.shape}, requires_grad {tens_2b_T.requires_grad}, dtype {tens_2b_T.dtype}, device {tens_2b_T.device}")
display(tens_2b_T)

tens_2_sum = tens_2a + tens_2b
tens_2_mul = tens_2a * tens_2b
tens_2_matmul = torch.matmul(tens_2a, tens_2b_T)

print(f"tens_2_sum ndim: {tens_2_sum.ndim}, shape {tens_2_sum.shape}, requires_grad {tens_2_sum.requires_grad}, dtype {tens_2_sum.dtype}, device {tens_2_sum.device}")
display(tens_2_sum)
print(f"tens_2_mul ndim: {tens_2_mul.ndim}, shape {tens_2_mul.shape}, requires_grad {tens_2_mul.requires_grad}, dtype {tens_2_mul.dtype}, device {tens_2_mul.device}")
display(tens_2_mul)
print(f"tens_2_matmul ndim: {tens_2_matmul.ndim}, shape {tens_2_matmul.shape}, requires_grad {tens_2_matmul.requires_grad}, dtype {tens_2_matmul.dtype}, device {tens_2_matmul.device}")
display(tens_2_matmul)


tens_2a ndim: 2, shape torch.Size([4, 2]), requires_grad False, dtype torch.float32, device cuda:0


tensor([[0.2716, 0.2912],
        [0.2154, 0.1459],
        [0.8024, 0.0452],
        [0.7345, 0.9042]], device='cuda:0')

tens_2b ndim: 2, shape torch.Size([4, 2]), requires_grad False, dtype torch.float32, device cuda:0


tensor([[0.6902, 0.2744],
        [0.2109, 0.2656],
        [0.5940, 0.6142],
        [0.8133, 0.8926]], device='cuda:0')

tens_2b_T ndim: 2, shape torch.Size([2, 4]), requires_grad False, dtype torch.float32, device cuda:0


tensor([[0.6902, 0.2109, 0.5940, 0.8133],
        [0.2744, 0.2656, 0.6142, 0.8926]], device='cuda:0')

tens_2_sum ndim: 2, shape torch.Size([4, 2]), requires_grad False, dtype torch.float32, device cuda:0


tensor([[0.9618, 0.5656],
        [0.4262, 0.4116],
        [1.3965, 0.6594],
        [1.5478, 1.7968]], device='cuda:0')

tens_2_mul ndim: 2, shape torch.Size([4, 2]), requires_grad False, dtype torch.float32, device cuda:0


tensor([[0.1874, 0.0799],
        [0.0454, 0.0388],
        [0.4767, 0.0277],
        [0.5974, 0.8071]], device='cuda:0')

tens_2_matmul ndim: 2, shape torch.Size([4, 4]), requires_grad False, dtype torch.float32, device cuda:0


tensor([[0.2674, 0.1346, 0.3402, 0.4808],
        [0.1887, 0.0842, 0.2176, 0.3054],
        [0.5662, 0.1812, 0.5044, 0.6930],
        [0.7550, 0.3951, 0.9917, 1.4045]], device='cuda:0')

In [26]:
tens_3a = torch.rand(size=(3,4,2), dtype=torch.float32, device='cuda', requires_grad=False)
tens_3b = torch.rand(size=(3,4,2), dtype=torch.float32, device='cuda', requires_grad=False)

In [27]:
print(f"tens_3a ndim: {tens_3a.ndim}, shape {tens_3a.shape}, requires_grad {tens_3a.requires_grad}, dtype {tens_3a.dtype}, device {tens_3a.device}")
display(tens_3a)
print(f"tens_3b ndim: {tens_3b.ndim}, shape {tens_3b.shape}, requires_grad {tens_3b.requires_grad}, dtype {tens_3b.dtype}, device {tens_3b.device}")
display(tens_3b)

tens_3b_T = tens_3b.transpose(2,1)
print(f"tens_3b_T ndim: {tens_3b_T.ndim}, shape {tens_3b_T.shape}, requires_grad {tens_3b_T.requires_grad}, dtype {tens_3b_T.dtype}, device {tens_3b_T.device}")
display(tens_3b_T)

tens_3_sum = tens_3a + tens_3b
tens_3_mul = tens_3a * tens_3b
tens_3_matmul = torch.matmul(tens_3a, tens_3b_T)

print(f"tens_3_sum ndim: {tens_3_sum.ndim}, shape {tens_3_sum.shape}, requires_grad {tens_3_sum.requires_grad}, dtype {tens_3_sum.dtype}, device {tens_3_sum.device}")
display(tens_3_sum)
print(f"tens_3_mul ndim: {tens_3_mul.ndim}, shape {tens_3_mul.shape}, requires_grad {tens_3_mul.requires_grad}, dtype {tens_3_mul.dtype}, device {tens_3_mul.device}")
display(tens_3_mul)
print(f"tens_3_matmul ndim: {tens_3_matmul.ndim}, shape {tens_3_matmul.shape}, requires_grad {tens_3_matmul.requires_grad}, dtype {tens_3_matmul.dtype}, device {tens_3_matmul.device}")
display(tens_3_matmul)


tens_3a ndim: 3, shape torch.Size([3, 4, 2]), requires_grad False, dtype torch.float32, device cuda:0


tensor([[[0.5328, 0.2786],
         [0.3585, 0.3866],
         [0.0892, 0.1502],
         [0.7887, 0.1483]],

        [[0.5356, 0.4796],
         [0.2085, 0.9336],
         [0.5298, 0.2109],
         [0.9995, 0.3354]],

        [[0.1678, 0.3359],
         [0.1941, 0.2531],
         [0.3602, 0.3886],
         [0.7860, 0.2344]]], device='cuda:0')

tens_3b ndim: 3, shape torch.Size([3, 4, 2]), requires_grad False, dtype torch.float32, device cuda:0


tensor([[[0.0631, 0.4734],
         [0.3554, 0.2453],
         [0.6107, 0.7567],
         [0.9150, 0.9248]],

        [[0.8995, 0.6415],
         [0.8965, 0.4093],
         [0.3902, 0.6331],
         [0.8656, 0.4075]],

        [[0.4163, 0.9704],
         [0.8618, 0.4396],
         [0.0889, 0.1247],
         [0.5987, 0.2378]]], device='cuda:0')

tens_3b_T ndim: 3, shape torch.Size([3, 2, 4]), requires_grad False, dtype torch.float32, device cuda:0


tensor([[[0.0631, 0.3554, 0.6107, 0.9150],
         [0.4734, 0.2453, 0.7567, 0.9248]],

        [[0.8995, 0.8965, 0.3902, 0.8656],
         [0.6415, 0.4093, 0.6331, 0.4075]],

        [[0.4163, 0.8618, 0.0889, 0.5987],
         [0.9704, 0.4396, 0.1247, 0.2378]]], device='cuda:0')

tens_3_sum ndim: 3, shape torch.Size([3, 4, 2]), requires_grad False, dtype torch.float32, device cuda:0


tensor([[[0.5959, 0.7520],
         [0.7139, 0.6319],
         [0.6999, 0.9069],
         [1.7036, 1.0731]],

        [[1.4351, 1.1210],
         [1.1050, 1.3429],
         [0.9200, 0.8440],
         [1.8651, 0.7430]],

        [[0.5840, 1.3063],
         [1.0559, 0.6926],
         [0.4492, 0.5133],
         [1.3847, 0.4722]]], device='cuda:0')

tens_3_mul ndim: 3, shape torch.Size([3, 4, 2]), requires_grad False, dtype torch.float32, device cuda:0


tensor([[[0.0336, 0.1319],
         [0.1274, 0.0948],
         [0.0545, 0.1136],
         [0.7216, 0.1371]],

        [[0.4818, 0.3076],
         [0.1870, 0.3821],
         [0.2067, 0.1335],
         [0.8652, 0.1367]],

        [[0.0698, 0.3259],
         [0.1673, 0.1112],
         [0.0320, 0.0485],
         [0.4706, 0.0557]]], device='cuda:0')

tens_3_matmul ndim: 3, shape torch.Size([3, 4, 4]), requires_grad False, dtype torch.float32, device cuda:0


tensor([[[0.1655, 0.2577, 0.5362, 0.7452],
         [0.2056, 0.2223, 0.5115, 0.6856],
         [0.0767, 0.0685, 0.1681, 0.2205],
         [0.1200, 0.3166, 0.5938, 0.8587]],

        [[0.7894, 0.6765, 0.5126, 0.6591],
         [0.7864, 0.5691, 0.6724, 0.5610],
         [0.6118, 0.5613, 0.3402, 0.5446],
         [1.1142, 1.0333, 0.6023, 1.0019]],

        [[0.3958, 0.2922, 0.0568, 0.1803],
         [0.3264, 0.2785, 0.0488, 0.1764],
         [0.5270, 0.4812, 0.0805, 0.3081],
         [0.5546, 0.7804, 0.0991, 0.5263]]], device='cuda:0')